SECRET_TOKEN:
DEVISE_SECRET:
DOMAIN_NAME:
ADMIN_EMAIL:
ADMIN_PASSWORD:
ADMIN_NAME:
#store information
STORE_NAME:
STORE_URL:
STORE_STATE:
DEFAULT_SEO_TITLE:
DEFAULT_SEO_DESCRIPTION:
DEFAULT_EMAIL_FROM:
MANDRILL_USERNAME:
MANDRILL_APIKEY:
production:
  SECRET_TOKEN:
  DEVISE_SECRET:
  DOMAIN_NAME:
  RACK_ENV:
  RAILS_ENV:
  EMAIL_USERNAME:
  EMAIL_PASSWORD:
